CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y
# CONFIG_POSIX_API=y

CONFIG_FLASH_BASE_ADDRESS=0x90000000
CONFIG_ROM_START_OFFSET=0x400
CONFIG_FLASH_LOAD_OFFSET=0x400

CONFIG_SHELL=y
CONFIG_I2C=y
CONFIG_I2C_SHELL=y

CONFIG_FPU=y
CONFIG_FP_HARDABI=y

CONFIG_LOG=y
CONFIG_ASSERT=y

CONFIG_DISPLAY=y
CONFIG_INPUT=y

CONFIG_MAIN_STACK_SIZE=32000

CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_XIP=y

# Configure SDL display to use RGB565 for better performance and compatibility
CONFIG_SDL_DISPLAY_DEFAULT_PIXEL_FORMAT_RGB_565=y